name: first-action

on:
  workflow-dispatch:
    inputs:
      environment:
        description: "fksdfd"
        required: true
        default: "sdf"
        options:
          - staging
          - dfdf

<<<<<<< HEAD
=======
      inputs:
        environment:
           description: "fksdfd"
   
           required: true
           default: "sdf"
           options:
            - staginf 
            - dfdf
>>>>>>> b1afb1ceee03d82d7a77955c949c84321715506a
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "itis working"

      - name: second-step
        run: echo "dfwjdf"

<<<<<<< HEAD
      - name: third-step
        run: echo "تعبت وربناا"
=======
     - name: second       
       run: echo " dfwjdf"


     - name: third
       run: echo "تعبت وربناا"
>>>>>>> b1afb1ceee03d82d7a77955c949c84321715506a
