
name: first-action

on:
  workflow-dispatch:

   inputs:
    environment:
     decription: "fksdfd"
 
     required: true
     default: "sdf"
     options:
      - staginf 
      - dfdf
  scheduele:
    - cron: "0 9 1 * *" 

jobs:
  tset:
    runs-on: ubuntu-latest

    steps:
     - name: checkout-code
       uses: actions/checkout@v3
     - name: first 
       run: echo "itis working"
     - name: second
       run: echo "  ${{gggg}}تعبت وربناا"