
name: first-action

on:
  push:
    branches:
       - main
       - master
    

jobs:
  tset:
    runs-on: ubuntu-latest
    steps:
     - name: first 
       run: echo "itis working"
     - name: second
       run: echo "تعبت وربناا"