
name: first-action

on:
  push:
    branches:
       - main
       - master
  pulll_request:
    branches:
       -master   

jobs:
  tset:
    runs-on: ubuntu-latest

    steps:
     - name: checkout-code
       uses: actions/checkout@v3
     - name: first 
       run: echo "itis working"
     - name: second
       run: echo "تعبت وربناا"