
name: first-action

on:

  workflow-dispatch:
    

      inputs:
        environment:
           description: "fksdfd"
   
           required: true
           default: "sdf"
           options:
            - staginf 
            - dfdf
jobs:
  tset:
    runs-on: ubuntu-latest

    steps:
     - name: first 
       run: echo "itis working"

  

     - name: second       
       run: echo " dfwjdf"


     - name: third
       run: echo "تعبت وربناا"
