on:
  push:

<<<<<<< Updated upstream
    branches:
      - main
      - master
    
=======
   inputs:
    environment:
     decription: "fksdfd"
 
     required: true
     default: "sdf"
     options:
      - staginf 
      - dfdf
  
>>>>>>> Stashed changes

jobs:
  tset:
    runs-on: ubuntu-latest


    steps:
     - name: first 
       run: echo "itis working"
<<<<<<< Updated upstream
  
=======
     - name: second
       run: echo " dfwjdf"
>>>>>>> Stashed changes
